- hosts: all
  vars_prompt:
     - name: dvd_dir
       private: no
       prompt: "enter dvd mount point"
  tasks:
  - file:
       state: directory
       path: "{{ dvd_dir }}"
  - mount:
       src: "/dev/cdrom"
       path: "{{ dvd_dir }}"
       state: mounted
       fstype: "iso9660"
  - yum_repository:
       baseurl: "{{ dvd_dir }}/AppStream"
       name: "mydvd1"
       description: "my dvd1 for pakage"
       gpgcheck: no
  - yum_repository:
       baseurl: "{{ dvd_dir }}/BaseOS"
       name: "mydvd2"
       description: "my dvd2 for pakage"
       gpgcheck: no
  - package:
       name: "httpd"
       state: present
  - file:
       state: directory
       path: "/var/www/suyog"
  - copy:
       src: "/root/ansible/playbook/new.conf"
       dest: "/etc/httpd/conf.d/new.conf"
  - copy:
       dest: "/var/www/suyog/index.html"
       content: "This is my web site\n"
  
  - name: "Restarting httpd Service"
    shell: "/usr/sbin/httpd"
    register: startoutput
    changed_when: "'already running' not in startoutput.stdout"
  - debug:
       msg: "{{startoutput.stdout}}"
    
  - firewalld:
       port: "8080/tcp"
       state: enabled
       permanent: yes
       immediate: yes

